services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin  
      - POSTGRES_HOST=localhost