services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
       POSTGRES_NAME: postgres
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin  
       POSTGRES_HOST: localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cardealer:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DBENGINE: postgres
      POSTGRES_NAME: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DJANGO_SETTINGS_MODULE: core.settings
      CORE_LOG_LEVEL: DEBUG