---
- name: Deploy the aplication
  hosts: aws
  become: true
  tasks:
    # Clone the repository
    - name: clone the repository
      git:
        repo: https://github.com/BroeDienz/cardealer.git
        dest: /home/ubuntu/app
        update: yes
    
    # Change directory to the cloned repository
    - name: Change directory to app folder
      command: chdir=/home/ubuntu/app pwd
    

    # install Docker Compose plugin
    - name: Install Docker Compose
      shell: |
        mkdir -p /usr/libexec/docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/libexec/docker/cli-plugins/docker-compose
        chmod +x /usr/libexec/docker/cli-plugins/docker-compose
      args:
        creates: /usr/libexec/docker/cli-plugins/docker-compose

    #deploy cardealer using docker compose
    - name: Deploy cardealer using docker compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/app
        state: present
        recreate: auto

     # Stop and remove existing containers
    - name: Stop and remove existing containers
      shell: docker-compose down
      args:
        chdir: /home/ubuntu/app
                
    # run Docker Compose
    - name: Run Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/app